webtalk_init -webtalk_dir /users/micasgst/ywang/Desktop/zed_proj/copy_zed_tpg/zed_tpg.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-08-15 16:22:56" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211253938_177879426_210696454_247" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l5k91ppdo06bdhnslanvkrqvhi" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.6.1810 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2655.615 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.609 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1565858481000" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1565858481000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key DebugCount -value "44" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1565878976195"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1565878976195"
webtalk_transmit -clientid 216510683 -regid "211253938_177879426_210696454_247" -xml /users/micasgst/ywang/Desktop/zed_proj/copy_zed_tpg/zed_tpg.sdk/webtalk/usage_statistics_ext_sdk.xml -html /users/micasgst/ywang/Desktop/zed_proj/copy_zed_tpg/zed_tpg.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /users/micasgst/ywang/Desktop/zed_proj/copy_zed_tpg/zed_tpg.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
